const languages = [
  {
    no: "0",
    name: "Auto",
    native: "Detect",
    code: "auto",
  },
  {
    no: "1",
    name: "Afrikaans",
    native: "Afrikaans",
    code: "af",
  },
  {
    no: "2",
    name: "Albanian",
    native: "Shqip",
    code: "sq",
  },
  {
    no: "3",
    name: "Arabic",
    native: "عربي",
    code: "ar",
  },
  {
    no: "4",
    name: "Armenian",
    native: "Հայերէն",
    code: "hy",
  },
  {
    no: "5",
    name: "Azerbaijani",
    native: "آذربایجان دیلی",
    code: "az",
  },
  {
    no: "6",
    name: "Basque",
    native: "Euskara",
    code: "eu",
  },
  {
    no: "7",
    name: "Belarusian",
    native: "Беларуская",
    code: "be",
  },
  {
    no: "8",
    name: "Bulgarian",
    native: "Български",
    code: "bg",
  },
  {
    no: "9",
    name: "Catalan",
    native: "Català",
    code: "ca",
  },
  {
    no: "10",
    name: "Chinese (Simplified)",
    native: "中文简体",
    code: "zh-CN",
  },
  {
    no: "11",
    name: "Chinese (Traditional)",
    native: "中文繁體",
    code: "zh-TW",
  },
  {
    no: "12",
    name: "Croatian",
    native: "Hrvatski",
    code: "hr",
  },
  {
    no: "13",
    name: "Czech",
    native: "Čeština",
    code: "cs",
  },
  {
    no: "14",
    name: "Danish",
    native: "Dansk",
    code: "da",
  },
  {
    no: "15",
    name: "Dutch",
    native: "Nederlands",
    code: "nl",
  },
  {
    no: "16",
    name: "English",
    native: "English",
    code: "en",
  },
  {
    no: "17",
    name: "Estonian",
    native: "Eesti keel",
    code: "et",
  },
  {
    no: "18",
    name: "Filipino",
    native: "Filipino",
    code: "tl",
  },
  {
    no: "19",
    name: "Finnish",
    native: "Suomi",
    code: "fi",
  },
  {
    no: "20",
    name: "French",
    native: "Français",
    code: "fr",
  },
  {
    no: "21",
    name: "Galician",
    native: "Galego",
    code: "gl",
  },
  {
    no: "22",
    name: "Georgian",
    native: "ქართული",
    code: "ka",
  },
  {
    no: "23",
    name: "German",
    native: "Deutsch",
    code: "de",
  },
  {
    no: "24",
    name: "Greek",
    native: "Ελληνικά",
    code: "el",
  },
  {
    no: "25",
    name: "Haitian Creole",
    native: "Kreyòl ayisyen",
    code: "ht",
  },
  {
    no: "26",
    name: "Hausa",
    native: "Harshen/Halshen Hausa هَرْشَن هَوْسَ",
    code: "ha",
  },
  {
    no: "27",
    name: "Hebrew",
    native: "עברית",
    code: "iw",
  },
  {
    no: "28",
    name: "Hindi",
    native: "हिन्दी",
    code: "hi",
  },
  {
    no: "29",
    name: "Hungarian",
    native: "Magyar",
    code: "hu",
  },
  {
    no: "30",
    name: "Icelandic",
    native: "Íslenska",
    code: "is",
  },
  {
    no: "31",
    name: "Igbo",
    native: "Asụsụ Igbo",
    code: "ig",
  },
  {
    no: "32",
    name: "Indonesian",
    native: "Bahasa Indonesia",
    code: "id",
  },
  {
    no: "33",
    name: "Irish",
    native: "Gaeilge",
    code: "ga",
  },
  {
    no: "35",
    name: "Italian",
    native: "Italiano",
    code: "it",
  },
  {
    no: "36",
    name: "Japanese",
    native: "日本語",
    code: "ja",
  },
  {
    no: "37",
    name: "Korean",
    native: "한국어",
    code: "ko",
  },
  {
    no: "38",
    name: "Latvian",
    native: "Latviešu",
    code: "lv",
  },
  {
    no: "39",
    name: "Lithuanian",
    native: "Lietuvių kalba",
    code: "lt",
  },
  {
    no: "40",
    name: "Macedonian",
    native: "Македонски",
    code: "mk",
  },
  {
    no: "41",
    name: "Malay",
    native: "Malay",
    code: "ms",
  },
  {
    no: "42",
    name: "Maltese",
    native: "Malti",
    code: "mt",
  },
  {
    no: "43",
    name: "Norwegian",
    native: "Norsk",
    code: "no",
  },
  {
    no: "44",
    name: "Persian",
    native: "فارسی",
    code: "fa",
  },
  {
    no: "45",
    name: "Polish",
    native: "Polski",
    code: "pl",
  },
  {
    no: "46",
    name: "Portuguese",
    native: "Português",
    code: "pt",
  },
  {
    no: "47",
    name: "Romanian",
    native: "Română",
    code: "ro",
  },
  {
    no: "48",
    name: "Russian",
    native: "Русский",
    code: "ru",
  },
  {
    no: "49",
    name: "Serbian",
    native: "Српски",
    code: "sr",
  },
  {
    no: "50",
    name: "Slovak",
    native: "Slovenčina",
    code: "sk",
  },
  {
    no: "51",
    name: "Slovenian",
    native: "Slovensko",
    code: "sl",
  },
  {
    no: "52",
    name: "Spanish",
    native: "Español",
    code: "es",
  },
  {
    no: "53",
    name: "Swahili",
    native: "Kiswahili",
    code: "sw",
  },
  {
    no: "54",
    name: "Swedish",
    native: "Svenska",
    code: "sv",
  },
  {
    no: "55",
    name: "Thai",
    native: "ไทย",
    code: "th",
  },
  {
    no: "56",
    name: "Turkish",
    native: "Türkçe",
    code: "tr",
  },
  {
    no: "57",
    name: "Ukrainian",
    native: "Українська",
    code: "uk",
  },
  {
    no: "58",
    name: "Urdu",
    native: "اردو",
    code: "ur",
  },
  {
    no: "59",
    name: "Vietnamese",
    native: "Tiếng Việt",
    code: "vi",
  },
  {
    no: "60",
    name: "Welsh",
    native: "Cymraeg",
    code: "cy",
  },
  {
    no: "61",
    name: "Yiddish",
    native: "ייִדיש",
    code: "yi",
  },
  {
    no: "62",
    name: "Yoruba",
    native: "Èdè Yorùbá",
    code: "yo",
  },
  {
    no: "63",
    name: "Zulu",
    native: "zulu",
    code: "zu",
  },
];
